Feat PECL
* feat: PECL
* feat: Samples to install extensions and install PECL from source

diff --git a/scripts/docker-php-ext-install b/scripts/docker-php-ext-install
--- a/scripts/docker-php-ext-install
+++ b/scripts/docker-php-ext-install
@@ -16,49 +16,59 @@ if [ -z "$srcExists" ]; then
 	touch /usr/src/php/.docker-delete-me
 fi
 
-cd /usr/src/php/ext
+cd /usr/src/php/php-src-master/ext
 
 usage() {
-	echo "usage: $0 [-jN] ext-name [ext-name ...]"
+	echo "Installs PHP extensions."
+	echo
+	echo "usage: $0 [-jN] [--ini-name file.ini] ext-name [ext-name ...]"
+	echo
 	echo "   ie: $0 gd mysqli"
 	echo "       $0 pdo pdo_mysql"
 	echo "       $0 -j5 gd mbstring mysqli pdo pdo_mysql shmop"
 	echo
+	echo "options:"
+	echo "   -j          Number of processors to use. Number of 'nproc' will be used by default."
+	echo "   --ini-name  Alternate php.ini for configuration."
+	echo
 	echo 'if custom ./configure arguments are necessary, see docker-php-ext-configure'
 	echo
 	echo 'Possible values for ext-name:'
+	printf '   '
 	find . \
-			-mindepth 2 \
-			-maxdepth 2 \
-			-type f \
-			-name 'config.m4' \
-		| xargs -n1 dirname \
-		| xargs -n1 basename \
-		| sort \
-		| xargs
+		-mindepth 2 \
+		-maxdepth 2 \
+		-type f \
+		-name 'config.m4' |
+		xargs -n1 dirname |
+		xargs -n1 basename |
+		sort |
+		xargs
 	echo
 	echo 'Some of the above modules are already compiled into PHP; please check'
 	echo 'the output of "php -i" to see which modules are already loaded.'
 }
 
-opts="$(getopt -o 'h?j:' --long 'help,jobs:' -- "$@" || { usage >&2 && false; })"
+opts="$(getopt -o 'h?j:' --long 'help,ini-name:,jobs:' -- "$@" || { usage >&2 && false; })"
 eval set -- "$opts"
 
-j=1
+j=$(nproc)
+iniName=
 while true; do
 	flag="$1"
 	shift
 	case "$flag" in
-		--help|-h|'-?') usage && exit 0 ;;
-		--jobs|-j) j="$1" && shift ;;
-		--) break ;;
-		*)
-			{
-				echo "error: unknown flag: $flag"
-				usage
-			} >&2
-			exit 1
-			;;
+	--help | -h | '-?') usage && exit 0 ;;
+	--ini-name) iniName="$1" && shift ;;
+	--jobs | -j) j="$1" && shift ;;
+	--) break ;;
+	*)
+		{
+			echo "error: unknown flag: $flag"
+			usage
+		} >&2
+		exit 1
+		;;
 	esac
 done
 
@@ -89,9 +99,9 @@ fi
 apkDel=
 if [ "$pm" = 'apk' ]; then
 	if [ -n "$PHPIZE_DEPS" ]; then
-		if apk info --installed .phpize-deps-configure > /dev/null; then
+		if apk info --installed .phpize-deps-configure >/dev/null; then
 			apkDel='.phpize-deps-configure'
-		elif ! apk info --installed .phpize-deps > /dev/null; then
+		elif ! apk info --installed .phpize-deps >/dev/null; then
 			apk add --no-cache --virtual .phpize-deps $PHPIZE_DEPS
 			apkDel='.phpize-deps'
 		fi
@@ -107,16 +117,18 @@ for ext in $exts; do
 	find modules \
 		-maxdepth 1 \
 		-name '*.so' \
-		-exec basename '{}' ';' \
-			| xargs -r docker-php-ext-enable
+		-exec basename '{}' ';' |
+		xargs -r docker-php-ext-enable ${iniName:+--ini-name "$iniName"}
 	make -j"$j" clean
 	cd "$popDir"
 done
 
 if [ "$pm" = 'apk' ] && [ -n "$apkDel" ]; then
+	echo 'Deleting temporary apk packages ...'
 	apk del --no-network $apkDel
 fi
 
 if [ -e /usr/src/php/.docker-delete-me ]; then
+	echo 'Deleting extracted PHP source ...'
 	docker-php-source delete
 fi
